/** Switch Button */
export const ANIMATION_DURATION = 500;
export const SWITCH_CONTAINER_WIDTH = 150;
export const SUN_AND_MOON_SIZE = SWITCH_CONTAINER_WIDTH / 4;
export const SWITCH_CONTAINER_HEIGHT = SWITCH_CONTAINER_WIDTH / 2.4;
export const SWITCH_PADDING_HORIZONTAL = (SWITCH_CONTAINER_WIDTH * 8) / 100;
export const TRANSLATE_X =
  -SWITCH_CONTAINER_WIDTH + SUN_AND_MOON_SIZE + 2 * SWITCH_PADDING_HORIZONTAL;
